name: matrix-test

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment name'     
        required: true
        default: 'dev' 
env:
  environment: ${{ github.event.inputs.env || 'dev' }}

jobs:
  gen-matrix:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run changed-files with dir_names
      id: diff
      uses: tj-actions/changed-files@v35
      with:
        files: |
          app1
          app3
          tests/test2
        dir_names: "true"
        dir_names_exclude_root: true
        separator: ";"
        json: true
    outputs:
      matrix: ${{steps.diff.outputs.all_changed_files}}
    
  test:
    # strategy:
    #   matrix:
    #     service_name: ${{ fromJson(needs.gen-matrix.outputs.matrix) }}
    runs-on: ubuntu-22.04
    needs: gen-matrix
    steps:
      - name: Echo 
      # ${{ matrix.service_name }}
        run: |
          echo matrix -- > ${{needs.gen-matrix.outputs.matrix}}
          # echo name --> ${{ matrix.service_name }}
          # echo settings --> ${{ matrix.params.settings }}
          # echo values --> ${{ matrix.params.values }}-${{env.environment}}
